# Generated by Django 4.1 on 2022-11-13 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("portfolio_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("initial_account_balance", models.PositiveIntegerField()),
                ("balance", models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("stock_id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=28)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("is_enabled", models.BooleanField(null=True)),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("N/A", "Regular stock"),
                            ("crypto", "Crypto currency"),
                        ],
                        default="N/A",
                        max_length=16,
                    ),
                ),
                ("iex_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("trade_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.PositiveIntegerField()),
                ("volume", models.PositiveIntegerField()),
                ("trade_type", models.IntegerField(choices=[(1, "Buy"), (2, "Sell")])),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioStocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.PositiveIntegerField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
    ]
